package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALLERGY.
 */
public class Allergy {

    private Long id;
    private String ID;
    private String NAME;
    private String ParentID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Allergy() {
    }

    public Allergy(Long id) {
        this.id = id;
    }

    public Allergy(Long id, String ID, String NAME, String ParentID) {
        this.id = id;
        this.ID = ID;
        this.NAME = NAME;
        this.ParentID = ParentID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getNAME() {
        return NAME;
    }

    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public String getParentID() {
        return ParentID;
    }

    public void setParentID(String ParentID) {
        this.ParentID = ParentID;
    }

    // KEEP METHODS - put your custom methods here
     @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return NAME;
    }
    // KEEP METHODS END

}
