package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;

// KEEP INCLUDES END
/**
 * Entity mapped to table APPOINTMENT.
 */
public class Appointment {

	private Long id;
	private String user_id;
	private String bkid;
	private String pid;
	private String slotid;
	private String flag;
	private String apflag;
	private String followid;
	private String aptdate;
	private String reason;
	private String wid;
	private String wistep;
	private String wiid;
	private String visit;
	private String epid;
	private String siid;
	private String mpid;
	private java.util.Date creationdate;
	private String note;
	private String type;
	private String pfId;

	// KEEP FIELDS - put your custom fields here
	public Date aptDate;

	// KEEP FIELDS END

	public Appointment() {
	}

	public Appointment(Long id) {
		this.id = id;
	}

	public Appointment(Long id, String user_id, String bkid, String pid,
			String slotid, String flag, String apflag, String followid,
			String aptdate, String reason, String wid, String wistep,
			String wiid, String visit, String epid, String siid, String mpid,
			java.util.Date creationdate, String note, String type, String pfId) {
		this.id = id;
		this.user_id = user_id;
		this.bkid = bkid;
		this.pid = pid;
		this.slotid = slotid;
		this.flag = flag;
		this.apflag = apflag;
		this.followid = followid;
		this.aptdate = aptdate;
		this.reason = reason;
		this.wid = wid;
		this.wistep = wistep;
		this.wiid = wiid;
		this.visit = visit;
		this.epid = epid;
		this.siid = siid;
		this.mpid = mpid;
		this.creationdate = creationdate;
		this.note = note;
		this.type = type;
		this.pfId = pfId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public String getBkid() {
		return bkid;
	}

	public void setBkid(String bkid) {
		this.bkid = bkid;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getSlotid() {
		return slotid;
	}

	public void setSlotid(String slotid) {
		this.slotid = slotid;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getApflag() {
		return apflag;
	}

	public void setApflag(String apflag) {
		this.apflag = apflag;
	}

	public String getFollowid() {
		return followid;
	}

	public void setFollowid(String followid) {
		this.followid = followid;
	}

	public String getAptdate() {
		return aptdate;
	}

	public void setAptdate(String aptdate) {
		this.aptdate = aptdate;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getWid() {
		return wid;
	}

	public void setWid(String wid) {
		this.wid = wid;
	}

	public String getWistep() {
		return wistep;
	}

	public void setWistep(String wistep) {
		this.wistep = wistep;
	}

	public String getWiid() {
		return wiid;
	}

	public void setWiid(String wiid) {
		this.wiid = wiid;
	}

	public String getVisit() {
		return visit;
	}

	public void setVisit(String visit) {
		this.visit = visit;
	}

	public String getEpid() {
		return epid;
	}

	public void setEpid(String epid) {
		this.epid = epid;
	}

	public String getSiid() {
		return siid;
	}

	public void setSiid(String siid) {
		this.siid = siid;
	}

	public String getMpid() {
		return mpid;
	}

	public void setMpid(String mpid) {
		this.mpid = mpid;
	}

	public java.util.Date getCreationdate() {
		return creationdate;
	}

	public void setCreationdate(java.util.Date creationdate) {
		this.creationdate = creationdate;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPfId() {
		return pfId;
	}

	public void setPfId(String pfId) {
		this.pfId = pfId;
	}

	// KEEP METHODS - put your custom methods here
	public Date getApt_Date() {
		return aptDate;
	}

	public void setApt_Date(Date aptDate) {
		this.aptDate = aptDate;
	}
	// KEEP METHODS END

}
