package com.ezhealthtrack.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ezhealthtrack.greendao.Country;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COUNTRY.
*/
public class CountryDao extends AbstractDao<Country, Long> {

    public static final String TABLENAME = "COUNTRY";

    /**
     * Properties of entity Country.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property COUNTRY_ID = new Property(1, String.class, "COUNTRY_ID", false, "COUNTRY__ID");
        public final static Property COUNTRY_NAME = new Property(2, String.class, "COUNTRY_NAME", false, "COUNTRY__NAME");
        public final static Property COUNTRY_CODE = new Property(3, String.class, "COUNTRY_CODE", false, "COUNTRY__CODE");
        public final static Property DATE_UPDATED = new Property(4, String.class, "DATE_UPDATED", false, "DATE__UPDATED");
        public final static Property DATE_CREATED = new Property(5, String.class, "DATE_CREATED", false, "DATE__CREATED");
    };


    public CountryDao(DaoConfig config) {
        super(config);
    }
    
    public CountryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COUNTRY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'COUNTRY__ID' TEXT," + // 1: COUNTRY_ID
                "'COUNTRY__NAME' TEXT," + // 2: COUNTRY_NAME
                "'COUNTRY__CODE' TEXT," + // 3: COUNTRY_CODE
                "'DATE__UPDATED' TEXT," + // 4: DATE_UPDATED
                "'DATE__CREATED' TEXT);"); // 5: DATE_CREATED
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COUNTRY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Country entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String COUNTRY_ID = entity.getCOUNTRY_ID();
        if (COUNTRY_ID != null) {
            stmt.bindString(2, COUNTRY_ID);
        }
 
        String COUNTRY_NAME = entity.getCOUNTRY_NAME();
        if (COUNTRY_NAME != null) {
            stmt.bindString(3, COUNTRY_NAME);
        }
 
        String COUNTRY_CODE = entity.getCOUNTRY_CODE();
        if (COUNTRY_CODE != null) {
            stmt.bindString(4, COUNTRY_CODE);
        }
 
        String DATE_UPDATED = entity.getDATE_UPDATED();
        if (DATE_UPDATED != null) {
            stmt.bindString(5, DATE_UPDATED);
        }
 
        String DATE_CREATED = entity.getDATE_CREATED();
        if (DATE_CREATED != null) {
            stmt.bindString(6, DATE_CREATED);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Country readEntity(Cursor cursor, int offset) {
        Country entity = new Country( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // COUNTRY_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // COUNTRY_NAME
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // COUNTRY_CODE
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DATE_UPDATED
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // DATE_CREATED
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Country entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCOUNTRY_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCOUNTRY_NAME(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCOUNTRY_CODE(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDATE_UPDATED(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDATE_CREATED(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Country entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Country entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
