package com.ezhealthtrack.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ezhealthtrack.greendao.Icd10Item;
import com.ezhealthtrack.greendao.Labs;
import com.ezhealthtrack.greendao.Radiology;
import com.ezhealthtrack.greendao.Area;
import com.ezhealthtrack.greendao.City;
import com.ezhealthtrack.greendao.Country;
import com.ezhealthtrack.greendao.State;
import com.ezhealthtrack.greendao.Patient;
import com.ezhealthtrack.greendao.Appointment;
import com.ezhealthtrack.greendao.User;
import com.ezhealthtrack.greendao.SoapNote;
import com.ezhealthtrack.greendao.MasterSoapNote;
import com.ezhealthtrack.greendao.Allergy;
import com.ezhealthtrack.greendao.MessageModel;
import com.ezhealthtrack.greendao.LabAppointment;
import com.ezhealthtrack.greendao.PatientShow;
import com.ezhealthtrack.greendao.Order;
import com.ezhealthtrack.greendao.OrderDetail;
import com.ezhealthtrack.greendao.LabTechnician;
import com.ezhealthtrack.greendao.LabWorkFlow;
import com.ezhealthtrack.greendao.MedRecVisitNotes;
import com.ezhealthtrack.greendao.MedRecAllergy;

import com.ezhealthtrack.greendao.Icd10ItemDao;
import com.ezhealthtrack.greendao.LabsDao;
import com.ezhealthtrack.greendao.RadiologyDao;
import com.ezhealthtrack.greendao.AreaDao;
import com.ezhealthtrack.greendao.CityDao;
import com.ezhealthtrack.greendao.CountryDao;
import com.ezhealthtrack.greendao.StateDao;
import com.ezhealthtrack.greendao.PatientDao;
import com.ezhealthtrack.greendao.AppointmentDao;
import com.ezhealthtrack.greendao.UserDao;
import com.ezhealthtrack.greendao.SoapNoteDao;
import com.ezhealthtrack.greendao.MasterSoapNoteDao;
import com.ezhealthtrack.greendao.AllergyDao;
import com.ezhealthtrack.greendao.MessageModelDao;
import com.ezhealthtrack.greendao.LabAppointmentDao;
import com.ezhealthtrack.greendao.PatientShowDao;
import com.ezhealthtrack.greendao.OrderDao;
import com.ezhealthtrack.greendao.OrderDetailDao;
import com.ezhealthtrack.greendao.LabTechnicianDao;
import com.ezhealthtrack.greendao.LabWorkFlowDao;
import com.ezhealthtrack.greendao.MedRecVisitNotesDao;
import com.ezhealthtrack.greendao.MedRecAllergyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig icd10ItemDaoConfig;
    private final DaoConfig labsDaoConfig;
    private final DaoConfig radiologyDaoConfig;
    private final DaoConfig areaDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig stateDaoConfig;
    private final DaoConfig patientDaoConfig;
    private final DaoConfig appointmentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig soapNoteDaoConfig;
    private final DaoConfig masterSoapNoteDaoConfig;
    private final DaoConfig allergyDaoConfig;
    private final DaoConfig messageModelDaoConfig;
    private final DaoConfig labAppointmentDaoConfig;
    private final DaoConfig patientShowDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig orderDetailDaoConfig;
    private final DaoConfig labTechnicianDaoConfig;
    private final DaoConfig labWorkFlowDaoConfig;
    private final DaoConfig medRecVisitNotesDaoConfig;
    private final DaoConfig medRecAllergyDaoConfig;

    private final Icd10ItemDao icd10ItemDao;
    private final LabsDao labsDao;
    private final RadiologyDao radiologyDao;
    private final AreaDao areaDao;
    private final CityDao cityDao;
    private final CountryDao countryDao;
    private final StateDao stateDao;
    private final PatientDao patientDao;
    private final AppointmentDao appointmentDao;
    private final UserDao userDao;
    private final SoapNoteDao soapNoteDao;
    private final MasterSoapNoteDao masterSoapNoteDao;
    private final AllergyDao allergyDao;
    private final MessageModelDao messageModelDao;
    private final LabAppointmentDao labAppointmentDao;
    private final PatientShowDao patientShowDao;
    private final OrderDao orderDao;
    private final OrderDetailDao orderDetailDao;
    private final LabTechnicianDao labTechnicianDao;
    private final LabWorkFlowDao labWorkFlowDao;
    private final MedRecVisitNotesDao medRecVisitNotesDao;
    private final MedRecAllergyDao medRecAllergyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        icd10ItemDaoConfig = daoConfigMap.get(Icd10ItemDao.class).clone();
        icd10ItemDaoConfig.initIdentityScope(type);

        labsDaoConfig = daoConfigMap.get(LabsDao.class).clone();
        labsDaoConfig.initIdentityScope(type);

        radiologyDaoConfig = daoConfigMap.get(RadiologyDao.class).clone();
        radiologyDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        stateDaoConfig = daoConfigMap.get(StateDao.class).clone();
        stateDaoConfig.initIdentityScope(type);

        patientDaoConfig = daoConfigMap.get(PatientDao.class).clone();
        patientDaoConfig.initIdentityScope(type);

        appointmentDaoConfig = daoConfigMap.get(AppointmentDao.class).clone();
        appointmentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        soapNoteDaoConfig = daoConfigMap.get(SoapNoteDao.class).clone();
        soapNoteDaoConfig.initIdentityScope(type);

        masterSoapNoteDaoConfig = daoConfigMap.get(MasterSoapNoteDao.class).clone();
        masterSoapNoteDaoConfig.initIdentityScope(type);

        allergyDaoConfig = daoConfigMap.get(AllergyDao.class).clone();
        allergyDaoConfig.initIdentityScope(type);

        messageModelDaoConfig = daoConfigMap.get(MessageModelDao.class).clone();
        messageModelDaoConfig.initIdentityScope(type);

        labAppointmentDaoConfig = daoConfigMap.get(LabAppointmentDao.class).clone();
        labAppointmentDaoConfig.initIdentityScope(type);

        patientShowDaoConfig = daoConfigMap.get(PatientShowDao.class).clone();
        patientShowDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        orderDetailDaoConfig = daoConfigMap.get(OrderDetailDao.class).clone();
        orderDetailDaoConfig.initIdentityScope(type);

        labTechnicianDaoConfig = daoConfigMap.get(LabTechnicianDao.class).clone();
        labTechnicianDaoConfig.initIdentityScope(type);

        labWorkFlowDaoConfig = daoConfigMap.get(LabWorkFlowDao.class).clone();
        labWorkFlowDaoConfig.initIdentityScope(type);

        medRecVisitNotesDaoConfig = daoConfigMap.get(MedRecVisitNotesDao.class).clone();
        medRecVisitNotesDaoConfig.initIdentityScope(type);

        medRecAllergyDaoConfig = daoConfigMap.get(MedRecAllergyDao.class).clone();
        medRecAllergyDaoConfig.initIdentityScope(type);

        icd10ItemDao = new Icd10ItemDao(icd10ItemDaoConfig, this);
        labsDao = new LabsDao(labsDaoConfig, this);
        radiologyDao = new RadiologyDao(radiologyDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        stateDao = new StateDao(stateDaoConfig, this);
        patientDao = new PatientDao(patientDaoConfig, this);
        appointmentDao = new AppointmentDao(appointmentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        soapNoteDao = new SoapNoteDao(soapNoteDaoConfig, this);
        masterSoapNoteDao = new MasterSoapNoteDao(masterSoapNoteDaoConfig, this);
        allergyDao = new AllergyDao(allergyDaoConfig, this);
        messageModelDao = new MessageModelDao(messageModelDaoConfig, this);
        labAppointmentDao = new LabAppointmentDao(labAppointmentDaoConfig, this);
        patientShowDao = new PatientShowDao(patientShowDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        orderDetailDao = new OrderDetailDao(orderDetailDaoConfig, this);
        labTechnicianDao = new LabTechnicianDao(labTechnicianDaoConfig, this);
        labWorkFlowDao = new LabWorkFlowDao(labWorkFlowDaoConfig, this);
        medRecVisitNotesDao = new MedRecVisitNotesDao(medRecVisitNotesDaoConfig, this);
        medRecAllergyDao = new MedRecAllergyDao(medRecAllergyDaoConfig, this);

        registerDao(Icd10Item.class, icd10ItemDao);
        registerDao(Labs.class, labsDao);
        registerDao(Radiology.class, radiologyDao);
        registerDao(Area.class, areaDao);
        registerDao(City.class, cityDao);
        registerDao(Country.class, countryDao);
        registerDao(State.class, stateDao);
        registerDao(Patient.class, patientDao);
        registerDao(Appointment.class, appointmentDao);
        registerDao(User.class, userDao);
        registerDao(SoapNote.class, soapNoteDao);
        registerDao(MasterSoapNote.class, masterSoapNoteDao);
        registerDao(Allergy.class, allergyDao);
        registerDao(MessageModel.class, messageModelDao);
        registerDao(LabAppointment.class, labAppointmentDao);
        registerDao(PatientShow.class, patientShowDao);
        registerDao(Order.class, orderDao);
        registerDao(OrderDetail.class, orderDetailDao);
        registerDao(LabTechnician.class, labTechnicianDao);
        registerDao(LabWorkFlow.class, labWorkFlowDao);
        registerDao(MedRecVisitNotes.class, medRecVisitNotesDao);
        registerDao(MedRecAllergy.class, medRecAllergyDao);
    }
    
    public void clear() {
        icd10ItemDaoConfig.getIdentityScope().clear();
        labsDaoConfig.getIdentityScope().clear();
        radiologyDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        countryDaoConfig.getIdentityScope().clear();
        stateDaoConfig.getIdentityScope().clear();
        patientDaoConfig.getIdentityScope().clear();
        appointmentDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        soapNoteDaoConfig.getIdentityScope().clear();
        masterSoapNoteDaoConfig.getIdentityScope().clear();
        allergyDaoConfig.getIdentityScope().clear();
        messageModelDaoConfig.getIdentityScope().clear();
        labAppointmentDaoConfig.getIdentityScope().clear();
        patientShowDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        orderDetailDaoConfig.getIdentityScope().clear();
        labTechnicianDaoConfig.getIdentityScope().clear();
        labWorkFlowDaoConfig.getIdentityScope().clear();
        medRecVisitNotesDaoConfig.getIdentityScope().clear();
        medRecAllergyDaoConfig.getIdentityScope().clear();
    }

    public Icd10ItemDao getIcd10ItemDao() {
        return icd10ItemDao;
    }

    public LabsDao getLabsDao() {
        return labsDao;
    }

    public RadiologyDao getRadiologyDao() {
        return radiologyDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public StateDao getStateDao() {
        return stateDao;
    }

    public PatientDao getPatientDao() {
        return patientDao;
    }

    public AppointmentDao getAppointmentDao() {
        return appointmentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SoapNoteDao getSoapNoteDao() {
        return soapNoteDao;
    }

    public MasterSoapNoteDao getMasterSoapNoteDao() {
        return masterSoapNoteDao;
    }

    public AllergyDao getAllergyDao() {
        return allergyDao;
    }

    public MessageModelDao getMessageModelDao() {
        return messageModelDao;
    }

    public LabAppointmentDao getLabAppointmentDao() {
        return labAppointmentDao;
    }

    public PatientShowDao getPatientShowDao() {
        return patientShowDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public OrderDetailDao getOrderDetailDao() {
        return orderDetailDao;
    }

    public LabTechnicianDao getLabTechnicianDao() {
        return labTechnicianDao;
    }

    public LabWorkFlowDao getLabWorkFlowDao() {
        return labWorkFlowDao;
    }

    public MedRecVisitNotesDao getMedRecVisitNotesDao() {
        return medRecVisitNotesDao;
    }

    public MedRecAllergyDao getMedRecAllergyDao() {
        return medRecAllergyDao;
    }

}
