package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ICD10_ITEM.
 */
public class Icd10Item {

    private Long id;
    private String item_id;
    private String chapter_name;
    private String chapter_desc;
    private String section_id;
    private String section_desc;
    private String diag_parent_name;
    private String diag_parent_desc;
    private String diag_name;
    private String diag_desc;
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Icd10Item() {
    }

    public Icd10Item(Long id) {
        this.id = id;
    }

    public Icd10Item(Long id, String item_id, String chapter_name, String chapter_desc, String section_id, String section_desc, String diag_parent_name, String diag_parent_desc, String diag_name, String diag_desc, String status) {
        this.id = id;
        this.item_id = item_id;
        this.chapter_name = chapter_name;
        this.chapter_desc = chapter_desc;
        this.section_id = section_id;
        this.section_desc = section_desc;
        this.diag_parent_name = diag_parent_name;
        this.diag_parent_desc = diag_parent_desc;
        this.diag_name = diag_name;
        this.diag_desc = diag_desc;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItem_id() {
        return item_id;
    }

    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    public String getChapter_name() {
        return chapter_name;
    }

    public void setChapter_name(String chapter_name) {
        this.chapter_name = chapter_name;
    }

    public String getChapter_desc() {
        return chapter_desc;
    }

    public void setChapter_desc(String chapter_desc) {
        this.chapter_desc = chapter_desc;
    }

    public String getSection_id() {
        return section_id;
    }

    public void setSection_id(String section_id) {
        this.section_id = section_id;
    }

    public String getSection_desc() {
        return section_desc;
    }

    public void setSection_desc(String section_desc) {
        this.section_desc = section_desc;
    }

    public String getDiag_parent_name() {
        return diag_parent_name;
    }

    public void setDiag_parent_name(String diag_parent_name) {
        this.diag_parent_name = diag_parent_name;
    }

    public String getDiag_parent_desc() {
        return diag_parent_desc;
    }

    public void setDiag_parent_desc(String diag_parent_desc) {
        this.diag_parent_desc = diag_parent_desc;
    }

    public String getDiag_name() {
        return diag_name;
    }

    public void setDiag_name(String diag_name) {
        this.diag_name = diag_name;
    }

    public String getDiag_desc() {
        return diag_desc;
    }

    public void setDiag_desc(String diag_desc) {
        this.diag_desc = diag_desc;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
