package com.ezhealthtrack.greendao;

import com.ezhealthtrack.order.OrderView;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LAB_APPOINTMENT.
 */
public class LabAppointment {

	private Long id;
	private String user_id;
	private String bkid;
	private String pid;
	private String pfid;
	private String slotid;
	private String flag;
	private String apflag;
	private String followid;
	private java.util.Date aptdate;
	private String reason;
	private Integer assigned_user_type;
	private String addi_info;
	private String visit_location;
	private String assigned_user_id;
	private String visit;
	private String epid;

	// KEEP FIELDS - put your custom fields here
	public OrderView orderView = new OrderView();
	public PatientShow patient = new PatientShow();

	// KEEP FIELDS END

	public LabAppointment() {
	}

	public LabAppointment(Long id) {
		this.id = id;
	}

	public LabAppointment(Long id, String user_id, String bkid, String pid,
			String pfid, String slotid, String flag, String apflag,
			String followid, java.util.Date aptdate, String reason,
			Integer assigned_user_type, String addi_info,
			String visit_location, String assigned_user_id, String visit,
			String epid) {
		this.id = id;
		this.user_id = user_id;
		this.bkid = bkid;
		this.pid = pid;
		this.pfid = pfid;
		this.slotid = slotid;
		this.flag = flag;
		this.apflag = apflag;
		this.followid = followid;
		this.aptdate = aptdate;
		this.reason = reason;
		this.assigned_user_type = assigned_user_type;
		this.addi_info = addi_info;
		this.visit_location = visit_location;
		this.assigned_user_id = assigned_user_id;
		this.visit = visit;
		this.epid = epid;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public String getBkid() {
		return bkid;
	}

	public void setBkid(String bkid) {
		this.bkid = bkid;
	}

	public String getPid() {
		return pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getPfid() {
		return pfid;
	}

	public void setPfid(String pfid) {
		this.pfid = pfid;
	}

	public String getSlotid() {
		return slotid;
	}

	public void setSlotid(String slotid) {
		this.slotid = slotid;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getApflag() {
		return apflag;
	}

	public void setApflag(String apflag) {
		this.apflag = apflag;
	}

	public String getFollowid() {
		return followid;
	}

	public void setFollowid(String followid) {
		this.followid = followid;
	}

	public java.util.Date getAptdate() {
		return aptdate;
	}

	public void setAptdate(java.util.Date aptdate) {
		this.aptdate = aptdate;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Integer getAssigned_user_type() {
		return assigned_user_type;
	}

	public void setAssigned_user_type(Integer assigned_user_type) {
		this.assigned_user_type = assigned_user_type;
	}

	public String getAddi_info() {
		return addi_info;
	}

	public void setAddi_info(String addi_info) {
		this.addi_info = addi_info;
	}

	public String getVisit_location() {
		return visit_location;
	}

	public void setVisit_location(String visit_location) {
		this.visit_location = visit_location;
	}

	public String getAssigned_user_id() {
		return assigned_user_id;
	}

	public void setAssigned_user_id(String assigned_user_id) {
		this.assigned_user_id = assigned_user_id;
	}

	public String getVisit() {
		return visit;
	}

	public void setVisit(String visit) {
		this.visit = visit;
	}

	public String getEpid() {
		return epid;
	}

	public void setEpid(String epid) {
		this.epid = epid;
	}

	// KEEP METHODS - put your custom methods here

	// KEEP METHODS END

}
