package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LAB_WORK_FLOW.
 */
public class LabWorkFlow {

    private Long id;
    private String type;
    private String meta;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LabWorkFlow() {
    }

    public LabWorkFlow(Long id) {
        this.id = id;
    }

    public LabWorkFlow(Long id, String type, String meta) {
        this.id = id;
        this.type = type;
        this.meta = meta;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getMeta() {
        return meta;
    }

    public void setMeta(String meta) {
        this.meta = meta;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
