package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MED_REC_ALLERGY.
 */
public class MedRecAllergy {

    private Long id;
    private String pat_id;
    private String pat_detail;
    private String pat_unique_id;
    private String last_visit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MedRecAllergy() {
    }

    public MedRecAllergy(Long id) {
        this.id = id;
    }

    public MedRecAllergy(Long id, String pat_id, String pat_detail, String pat_unique_id, String last_visit) {
        this.id = id;
        this.pat_id = pat_id;
        this.pat_detail = pat_detail;
        this.pat_unique_id = pat_unique_id;
        this.last_visit = last_visit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPat_id() {
        return pat_id;
    }

    public void setPat_id(String pat_id) {
        this.pat_id = pat_id;
    }

    public String getPat_detail() {
        return pat_detail;
    }

    public void setPat_detail(String pat_detail) {
        this.pat_detail = pat_detail;
    }

    public String getPat_unique_id() {
        return pat_unique_id;
    }

    public void setPat_unique_id(String pat_unique_id) {
        this.pat_unique_id = pat_unique_id;
    }

    public String getLast_visit() {
        return last_visit;
    }

    public void setLast_visit(String last_visit) {
        this.last_visit = last_visit;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
