package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MED_REC_VISIT_NOTES.
 */
public class MedRecVisitNotes {

    private Long id;
    private String bk_id;
    private String pat_id;
    private String soap_id;
    private java.util.Date apt_date;
    private String reason;
    private String pat_detail;
    private String pat_unique_id;
    private String number_of_visit;
    private java.util.Date last_visit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MedRecVisitNotes() {
    }

    public MedRecVisitNotes(Long id) {
        this.id = id;
    }

    public MedRecVisitNotes(Long id, String bk_id, String pat_id, String soap_id, java.util.Date apt_date, String reason, String pat_detail, String pat_unique_id, String number_of_visit, java.util.Date last_visit) {
        this.id = id;
        this.bk_id = bk_id;
        this.pat_id = pat_id;
        this.soap_id = soap_id;
        this.apt_date = apt_date;
        this.reason = reason;
        this.pat_detail = pat_detail;
        this.pat_unique_id = pat_unique_id;
        this.number_of_visit = number_of_visit;
        this.last_visit = last_visit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBk_id() {
        return bk_id;
    }

    public void setBk_id(String bk_id) {
        this.bk_id = bk_id;
    }

    public String getPat_id() {
        return pat_id;
    }

    public void setPat_id(String pat_id) {
        this.pat_id = pat_id;
    }

    public String getSoap_id() {
        return soap_id;
    }

    public void setSoap_id(String soap_id) {
        this.soap_id = soap_id;
    }

    public java.util.Date getApt_date() {
        return apt_date;
    }

    public void setApt_date(java.util.Date apt_date) {
        this.apt_date = apt_date;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getPat_detail() {
        return pat_detail;
    }

    public void setPat_detail(String pat_detail) {
        this.pat_detail = pat_detail;
    }

    public String getPat_unique_id() {
        return pat_unique_id;
    }

    public void setPat_unique_id(String pat_unique_id) {
        this.pat_unique_id = pat_unique_id;
    }

    public String getNumber_of_visit() {
        return number_of_visit;
    }

    public void setNumber_of_visit(String number_of_visit) {
        this.number_of_visit = number_of_visit;
    }

    public java.util.Date getLast_visit() {
        return last_visit;
    }

    public void setLast_visit(java.util.Date last_visit) {
        this.last_visit = last_visit;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
