package com.ezhealthtrack.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ezhealthtrack.greendao.MedRecVisitNotes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MED_REC_VISIT_NOTES.
*/
public class MedRecVisitNotesDao extends AbstractDao<MedRecVisitNotes, Long> {

    public static final String TABLENAME = "MED_REC_VISIT_NOTES";

    /**
     * Properties of entity MedRecVisitNotes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Bk_id = new Property(1, String.class, "bk_id", false, "BK_ID");
        public final static Property Pat_id = new Property(2, String.class, "pat_id", false, "PAT_ID");
        public final static Property Soap_id = new Property(3, String.class, "soap_id", false, "SOAP_ID");
        public final static Property Apt_date = new Property(4, java.util.Date.class, "apt_date", false, "APT_DATE");
        public final static Property Reason = new Property(5, String.class, "reason", false, "REASON");
        public final static Property Pat_detail = new Property(6, String.class, "pat_detail", false, "PAT_DETAIL");
        public final static Property Pat_unique_id = new Property(7, String.class, "pat_unique_id", false, "PAT_UNIQUE_ID");
        public final static Property Number_of_visit = new Property(8, String.class, "number_of_visit", false, "NUMBER_OF_VISIT");
        public final static Property Last_visit = new Property(9, java.util.Date.class, "last_visit", false, "LAST_VISIT");
    };


    public MedRecVisitNotesDao(DaoConfig config) {
        super(config);
    }
    
    public MedRecVisitNotesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MED_REC_VISIT_NOTES' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BK_ID' TEXT," + // 1: bk_id
                "'PAT_ID' TEXT," + // 2: pat_id
                "'SOAP_ID' TEXT," + // 3: soap_id
                "'APT_DATE' INTEGER," + // 4: apt_date
                "'REASON' TEXT," + // 5: reason
                "'PAT_DETAIL' TEXT," + // 6: pat_detail
                "'PAT_UNIQUE_ID' TEXT," + // 7: pat_unique_id
                "'NUMBER_OF_VISIT' TEXT," + // 8: number_of_visit
                "'LAST_VISIT' INTEGER);"); // 9: last_visit
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MED_REC_VISIT_NOTES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MedRecVisitNotes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bk_id = entity.getBk_id();
        if (bk_id != null) {
            stmt.bindString(2, bk_id);
        }
 
        String pat_id = entity.getPat_id();
        if (pat_id != null) {
            stmt.bindString(3, pat_id);
        }
 
        String soap_id = entity.getSoap_id();
        if (soap_id != null) {
            stmt.bindString(4, soap_id);
        }
 
        java.util.Date apt_date = entity.getApt_date();
        if (apt_date != null) {
            stmt.bindLong(5, apt_date.getTime());
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(6, reason);
        }
 
        String pat_detail = entity.getPat_detail();
        if (pat_detail != null) {
            stmt.bindString(7, pat_detail);
        }
 
        String pat_unique_id = entity.getPat_unique_id();
        if (pat_unique_id != null) {
            stmt.bindString(8, pat_unique_id);
        }
 
        String number_of_visit = entity.getNumber_of_visit();
        if (number_of_visit != null) {
            stmt.bindString(9, number_of_visit);
        }
 
        java.util.Date last_visit = entity.getLast_visit();
        if (last_visit != null) {
            stmt.bindLong(10, last_visit.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MedRecVisitNotes readEntity(Cursor cursor, int offset) {
        MedRecVisitNotes entity = new MedRecVisitNotes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bk_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pat_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // soap_id
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // apt_date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // reason
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // pat_detail
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // pat_unique_id
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // number_of_visit
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)) // last_visit
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MedRecVisitNotes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBk_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPat_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSoap_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setApt_date(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setReason(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPat_detail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPat_unique_id(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setNumber_of_visit(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLast_visit(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MedRecVisitNotes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MedRecVisitNotes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
