package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MESSAGE_MODEL.
 */
public class MessageModel {

    private Long id;
    private String nid;
    private String data;
    private String context;
    private String context_type;
    private java.util.Date date;
    private String from_id;
    private String from_fam_id;
    private String from_type;
    private String nt_id;
    private String to_id;
    private String to_fam_id;
    private String to_type;
    private String notified;
    private String from_name;
    private String to_name;
    private Integer conv_count;
    private String message_type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MessageModel() {
    }

    public MessageModel(Long id) {
        this.id = id;
    }

    public MessageModel(Long id, String nid, String data, String context, String context_type, java.util.Date date, String from_id, String from_fam_id, String from_type, String nt_id, String to_id, String to_fam_id, String to_type, String notified, String from_name, String to_name, Integer conv_count, String message_type) {
        this.id = id;
        this.nid = nid;
        this.data = data;
        this.context = context;
        this.context_type = context_type;
        this.date = date;
        this.from_id = from_id;
        this.from_fam_id = from_fam_id;
        this.from_type = from_type;
        this.nt_id = nt_id;
        this.to_id = to_id;
        this.to_fam_id = to_fam_id;
        this.to_type = to_type;
        this.notified = notified;
        this.from_name = from_name;
        this.to_name = to_name;
        this.conv_count = conv_count;
        this.message_type = message_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public String getContext_type() {
        return context_type;
    }

    public void setContext_type(String context_type) {
        this.context_type = context_type;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getFrom_id() {
        return from_id;
    }

    public void setFrom_id(String from_id) {
        this.from_id = from_id;
    }

    public String getFrom_fam_id() {
        return from_fam_id;
    }

    public void setFrom_fam_id(String from_fam_id) {
        this.from_fam_id = from_fam_id;
    }

    public String getFrom_type() {
        return from_type;
    }

    public void setFrom_type(String from_type) {
        this.from_type = from_type;
    }

    public String getNt_id() {
        return nt_id;
    }

    public void setNt_id(String nt_id) {
        this.nt_id = nt_id;
    }

    public String getTo_id() {
        return to_id;
    }

    public void setTo_id(String to_id) {
        this.to_id = to_id;
    }

    public String getTo_fam_id() {
        return to_fam_id;
    }

    public void setTo_fam_id(String to_fam_id) {
        this.to_fam_id = to_fam_id;
    }

    public String getTo_type() {
        return to_type;
    }

    public void setTo_type(String to_type) {
        this.to_type = to_type;
    }

    public String getNotified() {
        return notified;
    }

    public void setNotified(String notified) {
        this.notified = notified;
    }

    public String getFrom_name() {
        return from_name;
    }

    public void setFrom_name(String from_name) {
        this.from_name = from_name;
    }

    public String getTo_name() {
        return to_name;
    }

    public void setTo_name(String to_name) {
        this.to_name = to_name;
    }

    public Integer getConv_count() {
        return conv_count;
    }

    public void setConv_count(Integer conv_count) {
        this.conv_count = conv_count;
    }

    public String getMessage_type() {
        return message_type;
    }

    public void setMessage_type(String message_type) {
        this.message_type = message_type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
