package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORDER_DETAIL.
 */
public class OrderDetail {

    private Long id;
    private Long order_id;
    private String technician_id;
    private String doctor;
    private String appointment_id;
    private String episode_id;
    private String order_notes;
    private String sampling_notes;
    private String sampling_on;
    private String sampling_done_notes;
    private String sampling_done_on;
    private String refund_status;
    private String publish_report;
    private String cancel_action;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrderDetail() {
    }

    public OrderDetail(Long id) {
        this.id = id;
    }

    public OrderDetail(Long id, Long order_id, String technician_id, String doctor, String appointment_id, String episode_id, String order_notes, String sampling_notes, String sampling_on, String sampling_done_notes, String sampling_done_on, String refund_status, String publish_report, String cancel_action) {
        this.id = id;
        this.order_id = order_id;
        this.technician_id = technician_id;
        this.doctor = doctor;
        this.appointment_id = appointment_id;
        this.episode_id = episode_id;
        this.order_notes = order_notes;
        this.sampling_notes = sampling_notes;
        this.sampling_on = sampling_on;
        this.sampling_done_notes = sampling_done_notes;
        this.sampling_done_on = sampling_done_on;
        this.refund_status = refund_status;
        this.publish_report = publish_report;
        this.cancel_action = cancel_action;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrder_id() {
        return order_id;
    }

    public void setOrder_id(Long order_id) {
        this.order_id = order_id;
    }

    public String getTechnician_id() {
        return technician_id;
    }

    public void setTechnician_id(String technician_id) {
        this.technician_id = technician_id;
    }

    public String getDoctor() {
        return doctor;
    }

    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }

    public String getAppointment_id() {
        return appointment_id;
    }

    public void setAppointment_id(String appointment_id) {
        this.appointment_id = appointment_id;
    }

    public String getEpisode_id() {
        return episode_id;
    }

    public void setEpisode_id(String episode_id) {
        this.episode_id = episode_id;
    }

    public String getOrder_notes() {
        return order_notes;
    }

    public void setOrder_notes(String order_notes) {
        this.order_notes = order_notes;
    }

    public String getSampling_notes() {
        return sampling_notes;
    }

    public void setSampling_notes(String sampling_notes) {
        this.sampling_notes = sampling_notes;
    }

    public String getSampling_on() {
        return sampling_on;
    }

    public void setSampling_on(String sampling_on) {
        this.sampling_on = sampling_on;
    }

    public String getSampling_done_notes() {
        return sampling_done_notes;
    }

    public void setSampling_done_notes(String sampling_done_notes) {
        this.sampling_done_notes = sampling_done_notes;
    }

    public String getSampling_done_on() {
        return sampling_done_on;
    }

    public void setSampling_done_on(String sampling_done_on) {
        this.sampling_done_on = sampling_done_on;
    }

    public String getRefund_status() {
        return refund_status;
    }

    public void setRefund_status(String refund_status) {
        this.refund_status = refund_status;
    }

    public String getPublish_report() {
        return publish_report;
    }

    public void setPublish_report(String publish_report) {
        this.publish_report = publish_report;
    }

    public String getCancel_action() {
        return cancel_action;
    }

    public void setCancel_action(String cancel_action) {
        this.cancel_action = cancel_action;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
