package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table PATIENT.
 */
public class Patient {

    // KEEP FIELDS - put your custom fields here
	private Long id;
	private String pid;
	private String pfn;
	private String pmn;
	private String pln;
	@SerializedName("p-mob-num")
	private String pmobnum;
	@SerializedName("p-email")
	private String pemail;
	@SerializedName("p-username")
	private String pusername;
	private String fid;
	@SerializedName("p-add1")
	private String padd1;
	@SerializedName("p-add2")
	private String padd2;
	@SerializedName("p-gender")
	private String pgender;
	@SerializedName("p-zip")
	private String pzip;
	@SerializedName("p-country")
	private String pcountry;
	@SerializedName("p-state")
	private String pstate;
	@SerializedName("p-city")
	private String pcity;
	@SerializedName("p-area")
	private String parea;
	private String uid;
	private String uid_type;
	@SerializedName("p-dob")
	private String pdob;
	@SerializedName("p-photo")
	private String pphoto;
	@SerializedName("p-age")
	private String page;
	@SerializedName("p-relation")
	private String prelation;
	@SerializedName("reg-date")
	private String reg_date;
	@SerializedName("last-visit")
	private java.util.Date lastvisit;
	private String full_name;
	private String haircolor;
	private String eyecolor;
	private String visiblemark;
	private String height;
	@SerializedName("p-country_id")
	private String pcountryid;
	@SerializedName("p-state_id")
	private String pstateid;
	@SerializedName("p-city_id")
	private String pcityid;
	@SerializedName("p-area_id")
	private String pareaid;
	private String p_detail;
	private String age;
	private String display_id;
    // KEEP FIELDS END

    public Patient() {
    }

    public Patient(Long id) {
        this.id = id;
    }

    public Patient(Long id, String pid, String pfn, String pmn, String pln, String pmobnum, String pemail, String pusername, String fid, String padd1, String padd2, String pgender, String pzip, String pcountry, String pstate, String pcity, String parea, String pcountryid, String pstateid, String pcityid, String pareaid, String uid, String uid_type, String pdob, String pphoto, String page, String prelation, String reg_date, java.util.Date lastvisit, String p_detail, String haircolor, String eyecolor, String visiblemark, String height, String display_id) {
        this.id = id;
        this.pid = pid;
        this.pfn = pfn;
        this.pmn = pmn;
        this.pln = pln;
        this.pmobnum = pmobnum;
        this.pemail = pemail;
        this.pusername = pusername;
        this.fid = fid;
        this.padd1 = padd1;
        this.padd2 = padd2;
        this.pgender = pgender;
        this.pzip = pzip;
        this.pcountry = pcountry;
        this.pstate = pstate;
        this.pcity = pcity;
        this.parea = parea;
        this.pcountryid = pcountryid;
        this.pstateid = pstateid;
        this.pcityid = pcityid;
        this.pareaid = pareaid;
        this.uid = uid;
        this.uid_type = uid_type;
        this.pdob = pdob;
        this.pphoto = pphoto;
        this.page = page;
        this.prelation = prelation;
        this.reg_date = reg_date;
        this.lastvisit = lastvisit;
        this.p_detail = p_detail;
        this.haircolor = haircolor;
        this.eyecolor = eyecolor;
        this.visiblemark = visiblemark;
        this.height = height;
        this.display_id = display_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getPfn() {
        return pfn;
    }

    public void setPfn(String pfn) {
        this.pfn = pfn;
    }

    public String getPmn() {
        return pmn;
    }

    public void setPmn(String pmn) {
        this.pmn = pmn;
    }

    public String getPln() {
        return pln;
    }

    public void setPln(String pln) {
        this.pln = pln;
    }

    public String getPmobnum() {
        return pmobnum;
    }

    public void setPmobnum(String pmobnum) {
        this.pmobnum = pmobnum;
    }

    public String getPemail() {
        return pemail;
    }

    public void setPemail(String pemail) {
        this.pemail = pemail;
    }

    public String getPusername() {
        return pusername;
    }

    public void setPusername(String pusername) {
        this.pusername = pusername;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getPadd1() {
        return padd1;
    }

    public void setPadd1(String padd1) {
        this.padd1 = padd1;
    }

    public String getPadd2() {
        return padd2;
    }

    public void setPadd2(String padd2) {
        this.padd2 = padd2;
    }

    public String getPgender() {
        return pgender;
    }

    public void setPgender(String pgender) {
        this.pgender = pgender;
    }

    public String getPzip() {
        return pzip;
    }

    public void setPzip(String pzip) {
        this.pzip = pzip;
    }

    public String getPcountry() {
        return pcountry;
    }

    public void setPcountry(String pcountry) {
        this.pcountry = pcountry;
    }

    public String getPstate() {
        return pstate;
    }

    public void setPstate(String pstate) {
        this.pstate = pstate;
    }

    public String getPcity() {
        return pcity;
    }

    public void setPcity(String pcity) {
        this.pcity = pcity;
    }

    public String getParea() {
        return parea;
    }

    public void setParea(String parea) {
        this.parea = parea;
    }

    public String getPcountryid() {
        return pcountryid;
    }

    public void setPcountryid(String pcountryid) {
        this.pcountryid = pcountryid;
    }

    public String getPstateid() {
        return pstateid;
    }

    public void setPstateid(String pstateid) {
        this.pstateid = pstateid;
    }

    public String getPcityid() {
        return pcityid;
    }

    public void setPcityid(String pcityid) {
        this.pcityid = pcityid;
    }

    public String getPareaid() {
        return pareaid;
    }

    public void setPareaid(String pareaid) {
        this.pareaid = pareaid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid_type() {
        return uid_type;
    }

    public void setUid_type(String uid_type) {
        this.uid_type = uid_type;
    }

    public String getPdob() {
        return pdob;
    }

    public void setPdob(String pdob) {
        this.pdob = pdob;
    }

    public String getPphoto() {
        return pphoto;
    }

    public void setPphoto(String pphoto) {
        this.pphoto = pphoto;
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    public String getPrelation() {
        return prelation;
    }

    public void setPrelation(String prelation) {
        this.prelation = prelation;
    }

    public String getReg_date() {
        return reg_date;
    }

    public void setReg_date(String reg_date) {
        this.reg_date = reg_date;
    }

    public java.util.Date getLastvisit() {
        return lastvisit;
    }

    public void setLastvisit(java.util.Date lastvisit) {
        this.lastvisit = lastvisit;
    }

    public String getP_detail() {
        return p_detail;
    }

    public void setP_detail(String p_detail) {
        this.p_detail = p_detail;
    }

    public String getHaircolor() {
        return haircolor;
    }

    public void setHaircolor(String haircolor) {
        this.haircolor = haircolor;
    }

    public String getEyecolor() {
        return eyecolor;
    }

    public void setEyecolor(String eyecolor) {
        this.eyecolor = eyecolor;
    }

    public String getVisiblemark() {
        return visiblemark;
    }

    public void setVisiblemark(String visiblemark) {
        this.visiblemark = visiblemark;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getDisplay_id() {
        return display_id;
    }

    public void setDisplay_id(String display_id) {
        this.display_id = display_id;
    }

    // KEEP METHODS - put your custom methods here
	public int getage() {
		return Integer.parseInt(age);
	}
    // KEEP METHODS END

}
