package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PATIENT_SHOW.
 */
public class PatientShow {

    private Long id;
    private String p_id;
    private String pf_id;
    private String p_type;
    private String pfn;
    private String pln;
    private String gender;
    private String age;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PatientShow() {
    }

    public PatientShow(Long id) {
        this.id = id;
    }

    public PatientShow(Long id, String p_id, String pf_id, String p_type, String pfn, String pln, String gender, String age) {
        this.id = id;
        this.p_id = p_id;
        this.pf_id = pf_id;
        this.p_type = p_type;
        this.pfn = pfn;
        this.pln = pln;
        this.gender = gender;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getP_id() {
        return p_id;
    }

    public void setP_id(String p_id) {
        this.p_id = p_id;
    }

    public String getPf_id() {
        return pf_id;
    }

    public void setPf_id(String pf_id) {
        this.pf_id = pf_id;
    }

    public String getP_type() {
        return p_type;
    }

    public void setP_type(String p_type) {
        this.p_type = p_type;
    }

    public String getPfn() {
        return pfn;
    }

    public void setPfn(String pfn) {
        this.pfn = pfn;
    }

    public String getPln() {
        return pln;
    }

    public void setPln(String pln) {
        this.pln = pln;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
