package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table STATE.
 */
public class State {

    private Long id;
    private String STATE_ID;
    private String STATE_CODE;
    private String STATE_NAME;
    private String COUNTRY_ID;
    private String DATE_UPDATED;
    private String DATE_CREATED;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public State() {
    }

    public State(Long id) {
        this.id = id;
    }

    public State(Long id, String STATE_ID, String STATE_CODE, String STATE_NAME, String COUNTRY_ID, String DATE_UPDATED, String DATE_CREATED) {
        this.id = id;
        this.STATE_ID = STATE_ID;
        this.STATE_CODE = STATE_CODE;
        this.STATE_NAME = STATE_NAME;
        this.COUNTRY_ID = COUNTRY_ID;
        this.DATE_UPDATED = DATE_UPDATED;
        this.DATE_CREATED = DATE_CREATED;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSTATE_ID() {
        return STATE_ID;
    }

    public void setSTATE_ID(String STATE_ID) {
        this.STATE_ID = STATE_ID;
    }

    public String getSTATE_CODE() {
        return STATE_CODE;
    }

    public void setSTATE_CODE(String STATE_CODE) {
        this.STATE_CODE = STATE_CODE;
    }

    public String getSTATE_NAME() {
        return STATE_NAME;
    }

    public void setSTATE_NAME(String STATE_NAME) {
        this.STATE_NAME = STATE_NAME;
    }

    public String getCOUNTRY_ID() {
        return COUNTRY_ID;
    }

    public void setCOUNTRY_ID(String COUNTRY_ID) {
        this.COUNTRY_ID = COUNTRY_ID;
    }

    public String getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    public void setDATE_UPDATED(String DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    public String getDATE_CREATED() {
        return DATE_CREATED;
    }

    public void setDATE_CREATED(String DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    // KEEP METHODS - put your custom methods here
    	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return STATE_NAME;
	}
    	
    	public State(Long id, String STATE_ID, String STATE_CODE, String STATE_NAME, String COUNTRY_ID) {
            this.id = id;
            this.STATE_ID = STATE_ID;
            this.STATE_CODE = STATE_CODE;
            this.STATE_NAME = STATE_NAME;
            this.COUNTRY_ID = COUNTRY_ID;
        }
    // KEEP METHODS END

}
