package com.ezhealthtrack.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ezhealthtrack.greendao.State;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STATE.
*/
public class StateDao extends AbstractDao<State, Long> {

    public static final String TABLENAME = "STATE";

    /**
     * Properties of entity State.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property STATE_ID = new Property(1, String.class, "STATE_ID", false, "STATE__ID");
        public final static Property STATE_CODE = new Property(2, String.class, "STATE_CODE", false, "STATE__CODE");
        public final static Property STATE_NAME = new Property(3, String.class, "STATE_NAME", false, "STATE__NAME");
        public final static Property COUNTRY_ID = new Property(4, String.class, "COUNTRY_ID", false, "COUNTRY__ID");
        public final static Property DATE_UPDATED = new Property(5, String.class, "DATE_UPDATED", false, "DATE__UPDATED");
        public final static Property DATE_CREATED = new Property(6, String.class, "DATE_CREATED", false, "DATE__CREATED");
    };


    public StateDao(DaoConfig config) {
        super(config);
    }
    
    public StateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STATE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'STATE__ID' TEXT," + // 1: STATE_ID
                "'STATE__CODE' TEXT," + // 2: STATE_CODE
                "'STATE__NAME' TEXT," + // 3: STATE_NAME
                "'COUNTRY__ID' TEXT," + // 4: COUNTRY_ID
                "'DATE__UPDATED' TEXT," + // 5: DATE_UPDATED
                "'DATE__CREATED' TEXT);"); // 6: DATE_CREATED
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STATE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, State entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String STATE_ID = entity.getSTATE_ID();
        if (STATE_ID != null) {
            stmt.bindString(2, STATE_ID);
        }
 
        String STATE_CODE = entity.getSTATE_CODE();
        if (STATE_CODE != null) {
            stmt.bindString(3, STATE_CODE);
        }
 
        String STATE_NAME = entity.getSTATE_NAME();
        if (STATE_NAME != null) {
            stmt.bindString(4, STATE_NAME);
        }
 
        String COUNTRY_ID = entity.getCOUNTRY_ID();
        if (COUNTRY_ID != null) {
            stmt.bindString(5, COUNTRY_ID);
        }
 
        String DATE_UPDATED = entity.getDATE_UPDATED();
        if (DATE_UPDATED != null) {
            stmt.bindString(6, DATE_UPDATED);
        }
 
        String DATE_CREATED = entity.getDATE_CREATED();
        if (DATE_CREATED != null) {
            stmt.bindString(7, DATE_CREATED);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public State readEntity(Cursor cursor, int offset) {
        State entity = new State( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // STATE_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // STATE_CODE
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // STATE_NAME
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // COUNTRY_ID
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // DATE_UPDATED
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // DATE_CREATED
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, State entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSTATE_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSTATE_CODE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSTATE_NAME(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCOUNTRY_ID(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDATE_UPDATED(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDATE_CREATED(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(State entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(State entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
