package com.ezhealthtrack.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String user_id;
    private String name;
    private String role_id;
    private String speciality;
    private String photo;
    private String lab_name;
    private String user_un_id;
    private String tenant_type;
    private String tenant_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String user_id, String name, String role_id, String speciality, String photo, String lab_name, String user_un_id, String tenant_type, String tenant_id) {
        this.id = id;
        this.user_id = user_id;
        this.name = name;
        this.role_id = role_id;
        this.speciality = speciality;
        this.photo = photo;
        this.lab_name = lab_name;
        this.user_un_id = user_un_id;
        this.tenant_type = tenant_type;
        this.tenant_id = tenant_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRole_id() {
        return role_id;
    }

    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    public String getSpeciality() {
        return speciality;
    }

    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getLab_name() {
        return lab_name;
    }

    public void setLab_name(String lab_name) {
        this.lab_name = lab_name;
    }

    public String getUser_un_id() {
        return user_un_id;
    }

    public void setUser_un_id(String user_un_id) {
        this.user_un_id = user_un_id;
    }

    public String getTenant_type() {
        return tenant_type;
    }

    public void setTenant_type(String tenant_type) {
        this.tenant_type = tenant_type;
    }

    public String getTenant_id() {
        return tenant_id;
    }

    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
